djreact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from notifier.views import HomeView
# from ../../poster import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^post/', views.BlogDetailView.as_view(), name='post_detail'),
    url(r'^poster/', include(("poster.urls", "poster"), namespace='posts')),
    url(r'^users/', include(("djangorest.urls", "djangorest"), namespace='users')),
    path('notif/', HomeView.as_view()),
    path('trains/', include(("trainsgame.urls", "djangorest"), namespace='trains')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'^view2/',
#         generic.TemplateView.as_view(template_name='view2.html')),
#     url(r'^$',
#         generic.TemplateView.as_view(template_name='view1.html')),
# ]

poster/urls.py
from django.contrib import admin
from django.conf.urls import include, url
# from ../../poster import views

from .views import (
	post_list,
)
urlpatterns = [
	url(r'^$', post_list, name='list'),
]

trainsgame/urls.py
from django.conf.urls import include, url
from .views import (
    beginOfGAme,
    log_in, log_out, sign_up, beginOfGAmeTest, addToRtcGroup, solidityTestTask)

urlpatterns = [
	# url(r'^$', UserViewSet.as_view(), name='us_list'),
    # url(r'^trains/', beginOfGAme, name='beginOfGAme'),
    url(r'^$', beginOfGAme, name='beginOfGAme'),
    #прописвываем переменную get
    # url(r'^/(?P<username>[^/]+)/$', beginOfGAme, name='beginOfGAme'),

    url(r'^test', beginOfGAmeTest, name='beginOfGAmeTest'),
    url(r'^solid', solidityTestTask, name='solidityTestTask'),
    url(r'^log_in/$', log_in, name='log_in'),
    url(r'^log_out/$', log_out, name='log_out'),
    url(r'^sign_up/$', sign_up, name='sign_up'),

    url(r'^addToRtcGroup/', addToRtcGroup, name='addToRtcGroup'),
]

templates/SingleDot.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<h2>{{ dd }}</h2>
<h2>{{sdot}}</h2>
<h2>{{ffff}}</h2>

{% endblock content %}

{% load render_bundle from webpack_loader %}

{% block main %}
     {#    Подключение channels#}
    <script src="{% static '/channels/js/websocketbridge.js' %}" type="text/javascript"></script>
    <script>
        const webSocketBridge = new channels.WebSocketBridge();
        const webSocketBridgePixi = new channels.WebSocketBridge();
        const webSocketBridgeTickTock = new channels.WebSocketBridge();
        const webSocketBridgeNotific = new channels.WebSocketBridge();
        const webSocketStartNotific = new channels.WebSocketBridge();
        const webSocketStartNotificWORedis = new channels.WebSocketBridge();


        document.addEventListener('DOMContentLoaded', function() {

          webSocketBridge.connect('/ws/');
          webSocketBridge.listen(function(action, stream) {
            console.log("RESPONSE:", action, stream);
          })
          document.ws = webSocketBridge; /* for debugging */

          webSocketBridgePixi.connect('/pixiConsumer/')
          webSocketBridgePixi.listen(function(action, stream) {
              //var dot = JSON.parse(action)
            console.log("RESPONSE_PIXI:", action['doter'] + "|" + action['text'] , stream);
          })

          webSocketBridgeTickTock.connect('/tickTockConsumer/')
          webSocketBridgeTickTock.listen(function(action, stream) {
              //var dot = JSON.parse(action)
            console.log("RESPONSE_TickTock:", action, stream);
          })

          webSocketBridgeNotific.connect('/notifications/');
          webSocketBridgeNotific.listen(function(action, stream) {
             console.log("RESPONSE_notifications:", action);
          });

          webSocketStartNotific.connect('/notificationsStart/')
          webSocketStartNotific.listen(function(action, stream) {
             console.log("RESPONSE_notificationsStart:", action);
          });

          webSocketStartNotificWORedis.connect('/notificationsWORedis/')
          webSocketStartNotificWORedis.listen(function(action, stream) {
             console.log("notificationsWORedis:", action);
          });

        })

         function sendToPixiConsumer(textIn) {
            text = textIn + 1;
           webSocketBridgePixi.send(text)
        }

        function sendToStartNotConsumer(textIn) {
            text = textIn + 1;
           webSocketStartNotific.send(text)
        }

        function sendToStartNotConsumerWORedis(textIn) {
            text = textIn + 1;
           webSocketStartNotificWORedis.send(text)
        }

        var text = "eeee"
    </script>

    <button onclick="sendToPixiConsumer(text)">pixiConsumer</button>
    <button onclick="sendToStartNotConsumer(text)">startNotConsumer</button>
    <button onclick="sendToStartNotConsumerWORedis(text)">startNotConsumerWORedis</button>

    {# {% render_bundle 'Pixi' %}#}
    <script src="{% static 'lib/pixi.min480.js' %}"></script>
    <script type="text/javascript">
        treasHuntJs = "{% static 'images/treasureHunter.json' %}"
        animalsJs = "{% static 'images/animals.json' %}"
        catImg = "{% static 'images/cat.png' %}"
        tileset = "{% static 'images/tileset.png' %}"
    </script>



{% render_bundle 'vendors' %}
{% render_bundle 'Pixi' %}



{% endblock %}

templates/TrainGameTest.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<h2>{{ dd }}</h2>


{% endblock content %}

{% load render_bundle from webpack_loader %}

{% block main %}


     {#    Подключение channels#}
    <script src="{% static '/channels/js/websocketbridge.js' %}" type="text/javascript"></script>

    <div id="AppMain"></div>
    {% render_bundle 'vendors' %}
{#    {% render_bundle 'AppMain' %}#}


{#    -------------------------------------------------------------------------------#}


    <script>

         var text = "eeee"
         let gameState = "stop"
        const webSocketBridgeGroup = new channels.WebSocketBridge();
        const webSocketBridgeStart = new channels.WebSocketBridge();
        const webSocketBridgeControl = new channels.WebSocketBridge();
        const webSocketBridgeReact = new channels.WebSocketBridge();


        document.addEventListener('DOMContentLoaded', function() {
          webSocketBridgeGroup.connect('/trainsGroupConsumer/');
            {#сразу конектимся#}
          {#webSocketBridge.send("hi")#}

          webSocketBridgeStart.connect('/startGameConsumer/');
          webSocketBridgeStart.listen(function(action, stream) {
             console.log("RESPONSE_notifications:", action);
          });

          webSocketBridgeControl.connect('/controlGameConsumer/');
          webSocketBridgeControl.listen(function(action, stream) {
             console.log("controlGameConsumer:", action);
             if(action["type"] == "redirect"){
                  console.log(window.location.host + action["value"] + "?next=" + window.location.pathname)
                 window.location.href = action["value"] + "?next=" + window.location.pathname
             }

          });

          webSocketBridgeReact.connect('/groupConsumerReact/');
          {#webSocketBridgeReact.send({});#}

        });


         window.addEventListener(
            "keydown", downHandler, false
         );

         function downHandler(event) {
            //alert(event.keyCode)
             let whereMove = ""
             if(event.keyCode == 38){
                 whereMove = "up";
             }else if(event.keyCode == 40) {
                 whereMove = "down";
             }else if(event.keyCode == 39) {
                 whereMove = "right";
             }else if(event.keyCode == 37){
                whereMove = "left";
             }else{
                 return;
             }
             var name =   document.getElementById("player_name").value
             var arena_num =   document.getElementById("arena_num").value
           webSocketBridgeControl.send({"type":"moveTrainChange", "name":name, "whereMove":whereMove, "arena_num":arena_num})
         }

         function startGame(textIn) {
            {#text = textIn + 1;#}
             console.log(textIn)
             var arena_num =   document.getElementById("arena_num").value
           webSocketBridgeStart.send(arena_num)
        }

         function changeGame(textIn) {
           gameState = textIn
            {#text = textIn + 1;#}
             var arena_num =   document.getElementById("arena_num").value
             console.log(textIn)
           var name =   document.getElementById("player_name").value
             if(textIn =="join"){
                 webSocketBridgeGroup.send(arena_num)
             }
           webSocketBridgeControl.send({"type":textIn, "name":name, "arena_num":arena_num })
        }
    </script>


        {% render_bundle 'AppMain' %}

    <button onclick="changeGame('clear')">clearGame</button><br/>
    <input id="arena_num" type="text" value="1" />Номер арены <br/>
    <input id="player_name" type="text" value="a1" />Имя <br/>
    <button onclick="changeGame('join')">joinGame</button>
    <button onclick="startGame('start')">startGame</button>
    <button onclick="changeGame('play')">playGame</button>
    <button onclick="changeGame('stop')">stopGame</button>

    {# {% render_bundle 'Pixi' %}#}
    <script src="{% static 'lib/pixi.min480.js' %}"></script>




    <script type="text/javascript">
        treasHuntJs = "{% static 'images/treasureHunter.json' %}"
        arrows = "{% static 'images/arrows-res.jpg' %}"
        animalsJs = "{% static 'images/animals.json' %}"
        catImg = "{% static 'images/cat.png' %}"
        tileset = "{% static 'images/tileset.png' %}"
        cubes = "{% static 'images/cubes.jpg' %}"
    </script>
    <div id="gameCont">
    </div>



{#{% render_bundle 'vendors' %}#}
{% render_bundle 'Train' %}



{% endblock main %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>TrainsGame</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{#      https://webcareer.ru/jquery-cookies-rabota-s-kukami-na-jquery.html#}
      <script src="{% static 'lib/jquery.cookie.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">#}
{#    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>#}
{#    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">#}
      <style>
           .modal {
              position: fixed;
              top: 0;
              left: 0;
              width:100%;
              height: 100%;
              background: rgba(0, 0, 0, 0.6);
            }

            .modal-main {
              position:fixed;
              background: white;
              width: 80%;
              height: auto;
              top:50%;
              left:50%;
              transform: translate(-50%,-50%);
            }

            .display-block {
              display: block;
            }

            .display-none {
              display: none;
            }

           .outer-float {
               position: relative;
           }

           .inner-float {
               float: left;
               width: 45%;
           }

           .clear-both {
                clear: both;
           }

}

        </style>

  </head>
  <body>
    <header class="page-header">
      <h1><a href="/">Tutorial</a></h1>
    </header>

    <script>
      $(function () {
        $('#myTab a:last').tab('show')
      })
    </script>

    <div class="content container">
      {% block content %}
      {% endblock content %}
        {% block main %}
      {% endblock main %}
    </div>
  </body>
</html>

templates/home.html
{% load staticfiles %}
<html>
  <head>
    <title>Notifier</title>
    <script src="{% static '/channels/js/websocketbridge.js' %}" type="text/javascript"></script>
  </head>
  <body>
    <h1>Notifier</h1>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      const webSocketBridge = new channels.WebSocketBridge();
      webSocketBridge.connect('/ws/');
      webSocketBridge.listen(function(action, stream) {
        console.log("RESPONSE:", action, stream);
      })
      document.ws = webSocketBridge; /* for debugging */
    })
    </script>
  </body>
</html>

templates/log_in.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'trains:log_in' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'trains:sign_up' %}">Sign up!</a></p>
{% endblock content %}


templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="post">
    <h2>{{ object.title }}</h2>
    <p>{{ object.text }}</p>
    <p>ккккккк</p>
  </div>
{% endblock content %}

{% load render_bundle from webpack_loader %}

{% block main %}
    <div id="App1"></div>
    {% render_bundle 'vendors' %}
    {% render_bundle 'App1' %}
{% endblock %}


templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'trains:sign_up' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>11 Already have an account? <a href="{% url 'trains:log_in' %}">Log in!</a></p>
  </form>
    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    {% endif %}

{% endblock content %}

{% block main %}
{% endblock main %}